import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.db.crud_camera import get_camera_by_id
from app.db.crud_notification import create_notification, mark_notification_as_read
from app.models.event import Event


class NotificationService:
    """Manages the dispatching and auditing of critical surveillance alerts."""

    CRITICAL_EVENT_TYPES = {
        "unknown_person_detected",
        "object_disappeared",
        "restricted_area_entered",
    }

    def __init__(self, db_session_factory=None) -> None:
        self._logger = logging.getLogger(self.__class__.__name__)
        self._settings = get_settings()
        from app.db.session import SessionLocal
        self._db_session_factory = db_session_factory or SessionLocal

    def process_event(self, db: Session, event: Event) -> None:
        """Processes a surveillance event, logging and dispatching alerts if critical."""
        if not event or not event.event_type:
            return

        if event.event_type not in self.CRITICAL_EVENT_TYPES:
            return

        self._logger.info("Processing critical event for notifications", extra={"event_id": event.id, "type": event.event_type})

        camera = get_camera_by_id(db, event.camera_id)
        location = camera.location if camera else "Unknown location"
        camera_name = camera.name if camera else f"Camera #{event.camera_id}"

        # Construct notification message
        if event.event_type == "unknown_person_detected":
            subject = f"[ALERT] Unknown Person Detected at {location}"
            message = f"Critical Alert: An unknown individual was detected by {camera_name} ({location})."
        elif event.event_type == "restricted_area_entered":
            subject = f"[ALERT] Restricted Area Intrusion at {location}"
            message = f"Critical Alert: Restricted area entry detected by {camera_name} ({location}). Unauthorized person detected."
        elif event.event_type == "object_disappeared":
            subject = f"[ALERT] Object Removed at {location}"
            message = f"Critical Alert: Object removal detected by {camera_name} ({location}). Details: {event.description or 'Tracked item is missing.'}"
        else:
            subject = f"[ALERT] Surveillance Notification"
            message = f"Alert generated by {camera_name}: {event.description or ''}"

        # 1. Persist notification in database
        notification = create_notification(
            db,
            event_id=event.id,
            notification_type=event.event_type,
            message=message,
            email_sent=False,
            email_recipient=self._settings.alert_to_email if self._settings.enable_email_alerts else None,
        )

        # 2. Dispatch email asynchronously if configured to avoid blocking processing
        if self._settings.enable_email_alerts:
            from datetime import timezone, datetime
            from app.services.alert_throttle import AlertThrottle

            throttle = AlertThrottle()
            event_time = event.timestamp or datetime.now(timezone.utc)
            
            is_allowed = throttle.should_fire(
                camera_id=event.camera_id,
                camera_name=camera_name,
                event_type=event.event_type,
                notification_id=notification.id,
                event_time=event_time,
                description=event.description or message,
            )

            if is_allowed:
                import threading
                import time

                timestamp_str = event_time.isoformat()
                email_body = f"{message}\n\nTimestamp: {timestamp_str}\nCamera: {camera_name}\nLocation: {location}\n\nThis is an automated message from your AI CCTV Surveillance system."

                def dispatch_async(notif_id: int, body_text: str):
                    max_email_retries = 3
                    backoff_base = 2.0
                    success = False

                    for attempt in range(max_email_retries + 1):
                        try:
                            success = self._send_email_alert(
                                subject=subject,
                                body=body_text,
                            )
                        except Exception as email_exc:
                            self._logger.error("Exception during SMTP email send: %s", email_exc)
                            success = False

                        db_thread = self._db_session_factory()
                        try:
                            from app.db.crud_notification import get_notification_by_id
                            from app.db.session import commit_with_retry
                            notif = get_notification_by_id(db_thread, notif_id)
                            if notif is not None:
                                notif.retry_count = attempt
                                if success:
                                    notif.email_sent = True
                                    notif.status = "SENT"
                                    commit_with_retry(db_thread)
                                    self._logger.info("Email alert dispatched successfully on attempt %s", attempt)
                                else:
                                    if attempt >= max_email_retries:
                                        notif.status = "FAILED"
                                        commit_with_retry(db_thread)
                                        self._logger.error("Email alert failed after maximum retries. Notification marked as FAILED.")
                                    else:
                                        notif.status = "RETRIES_EXCEEDED" if attempt >= max_email_retries else "PENDING"
                                        commit_with_retry(db_thread)
                                        self._logger.warning("Email alert attempt %s failed", attempt)
                        except Exception as err:
                            self._logger.error("Failed to update database in background thread: %s", err)
                        finally:
                            db_thread.close()

                        if success:
                            break

                        # Exponential backoff delay between attempts
                        if attempt < max_email_retries:
                            sleep_duration = backoff_base ** attempt
                            self._logger.info("Retrying email alert in %s seconds...", sleep_duration)
                            time.sleep(sleep_duration)

                try:
                    threading.Thread(
                        target=dispatch_async,
                        args=(notification.id, email_body),
                        name=f"alert-dispatch-{notification.id}",
                        daemon=True
                    ).start()
                except Exception as thread_exc:
                    self._logger.error("Failed to spawn background thread for email dispatch: %s", thread_exc)
            else:
                # Suppressed!
                if self._settings.alert_digest_minutes and self._settings.alert_digest_minutes > 0:
                    notification.status = "DIGEST_PENDING"
                else:
                    notification.status = "SUPPRESSED"
                db.commit()
                self._logger.info("Email alert suppressed due to active cooldown (event_id: %s, type: %s)", event.id, event.event_type)

    def _send_email_alert(self, subject: str, body: str) -> bool:
        """Sends an email alert using standard smtplib."""
        if not self._settings.smtp_host or not self._settings.alert_to_email:
            self._logger.warning("SMTP host or Alert email settings are empty. Skipping email.")
            return False

        msg = MIMEMultipart()
        msg["From"] = self._settings.smtp_user or "cctv@surveillance-system.local"
        msg["To"] = self._settings.alert_to_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        try:
            server = smtplib.SMTP(self._settings.smtp_host, self._settings.smtp_port, timeout=10)
            server.ehlo()
            if self._settings.smtp_port == 587:
                server.starttls()
                server.ehlo()
            if self._settings.smtp_user and self._settings.smtp_pass:
                server.login(self._settings.smtp_user, self._settings.smtp_pass)
            server.sendmail(msg["From"], self._settings.alert_to_email, msg.as_string())
            server.quit()
            return True
        except Exception as exc:
            self._logger.exception("SMTP email send failed: %s", exc)
            return False
